name: Scrap

on:
  workflow_dispatch:
  schedule:
    # Every 12th of the month at midnight.
    - cron: "0 0 12 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Checking out the repository.
      - name: Checkout repository.
        uses: actions/checkout@v2.3.4
      # Installing the Python version required.
      - name: Setup Python.
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          if [ -f deps.txt ]; then pip install -r deps.txt; fi
      # Running the script for scrapping.
      - name: Run the scrapping script.
        run: |
          python scrap.py
          git add rrats.json
          git config --global user.email "rratbot@example.com"
          git config --global user.name "rratbot"
          git commit -m "RRAT database updated: `date +'%Y-%m-%d %H:%M:%S'`" || true
      - name: Push the changes.
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
